Disabled use_blink_v8_binding_new_idl_interface.
When enabled, we get build errors in blink such as:

gen/third_party/blink/renderer/bindings/modules/v8/v8_shared_worker_global_scope.cc:4614:34: error: no member named 'isReportingObserversEnabled' in 'blink::ContextFeatureSettings'
       context_feature_settings->isReportingObserversEnabled())) {
       ~~~~~~~~~~~~~~~~~~~~~~~~  ^
1 error generated.

When searching cs.chromium.org for the file above in 86.0.4238.2 it
reports that the file doesn't exist for that version, which makes me
think that Chromium disables the use_blink_v8_binding_new_idl_interface
in their build as well.

Chromium change:

https://source.chromium.org/chromium/chromium/src/+/a17f8253fcbd27cad86a0afdebb3c830b965deb2

commit a17f8253fcbd27cad86a0afdebb3c830b965deb2
Author: Yuki Shiino <yukishiino@chromium.org>
Date:   Fri Aug 14 20:37:21 2020 +0000

    Reland "bind-gen: Switch to the new IDL interface implementation"

    This is a reland of e1dce34f9e52b908b6dfda35ffda5a2d5de3bfcf

    Original change's description:
    > bind-gen: Switch to the new IDL interface implementation
    >
    > Blink-V8 bindings team has been developing the new improved
    > Web IDL bindings system, and this patch enables the new
    > bindings implementation of Web IDL interfaces at build time.
    >
    > Note that other IDL definitions (buffer source types,
    > dictionaries, callback functions, etc.) are not affected and
    > the old bindings are still used for them.
    >
    > The new IDL interface implementation is not 100% compatible
    > with the old one, and we see the following changes/improvement
    > that are visible from author script.
    >
    > Behavioral changes:
    > - Cross origin attributes become accessor properties.
    > - Indexed/named properties' behaviors change.
    > - Legacy platform objects with indexed properties support
    >   @@iterator property.
    > - Maplike supports size() operation.
    > - [NoInterfaceObject] removes 'constructor' property.
    > - Some of error messages change.
    > For these changes, new behaviors are better conforming to
    > Web IDL specification.
    >
    > Non-behavioral changes:
    > - Keep-alive-GC optimization is removed.
    >
    > For performance, there is no major difference in speed perf
    > and -17KB improvement in APK binary size.
    >
    > Pinpoint results
    > https://pinpoint-dot-chromeperf.appspot.com/job/1230bdd8920000
    > https://pinpoint-dot-chromeperf.appspot.com/job/14b5b5d0920000
    > https://pinpoint-dot-chromeperf.appspot.com/job/12ca6424920000
    > https://pinpoint-dot-chromeperf.appspot.com/job/14e3aa48920000
    >
    > Bug: 839389