Removed no longer needed patch for devtools.
This patch was originally added due to error:

    TypeScript compilation failed. Used tsconfig src\out\Release\gen/third_party/devtools-frontend/src/front_end/common/color-tsconfig.json

    ../../../node_modules/@types/babel__generator/index.d.ts(9,20): error TS2307: Cannot find module '@babel/types'.
    ../../../node_modules/@types/babel__traverse/index.d.ts(10,20): error TS2307: Cannot find module '@babel/types'.
    ../../../node_modules/@types/babel__traverse/index.d.ts(30,5): error TS2411: Property 'scope' of type 'Scope | undefined' is not assignab e to string index type '(VisitNodeFunction<S, any> & VisitNodeFunction<S, any>) | (VisitNodeFunction<S, any> & VisitNodeObject<S, any>) | (VisitNodeObject<...> & VisitNodeFunction<...>) | (VisitNodeObject<...> & VisitNodeObject<...>) | undefined'.
    ../../../node_modules/@types/babel__traverse/index.d.ts(31,5): error TS2411: Property 'noScope' of type 'boolean | undefined' is not assi nable to string index type '(VisitNodeFunction<S, any> & VisitNodeFunction<S, any>) | (VisitNodeFunction<S, any> & VisitNodeObject<S, any>) | (VisitNodeObject<...> & VisitNodeFunction<...>) | (VisitNodeObject<...> & VisitNodeObject<...>) | undefined'.
    ../../../node_modules/@types/babel__template/index.d.ts(9,31): error TS2307: Cannot find module '@babel/parser'.
    ../../../node_modules/@types/babel__template/index.d.ts(10,54): error TS2307: Cannot find module '@babel/types'.
    ../../../node_modules/@types/babel__core/index.d.ts(13,20): error TS2307: Cannot find module '@babel/types'.
    ../../../node_modules/@types/babel__core/index.d.ts(14,31): error TS2307: Cannot find module '@babel/parser'.

The error doesn't appear to be happening any more without the patch.